# SAMPLE CONFIG
# Rename to "config.yml" and fill fields correctly to run application

url: "https://data.url.net/api/v2.5"
user: "jsmith"
pass: "Candycanelane123"
test_collection: "NameTest"
prod_collection: "NameExample"
data_source: "testfile.xlsx"